@baseUrl=http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "nameOfPersonResponsible": "Dener Araujo",
  "email": "dener@example.com",
  "city": "test city",
  "cep": "123",
  "address": "test street",
  "whatsapp": "4321",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"dener@example.com",
  "password":"123456"
}

###

# @name create_pet
POST {{baseUrl}}/pets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "New pet",
  "city": "new city",
  "about": "New about",
  "age": "5",
  "weight": "19",
  "breed": "Husky",
  "size": "big"
}

###